FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    cmake \
    g++ \
    gcovr \
    libpaho-mqtt-dev \
    libpaho-mqttpp-dev \
    libgtest-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

CMD ["bash"]
